### ISSUE TITLE
[Task] Create Teams API base

### ISSUE THREAD

**Issue by pingu2k4** [PinguApps/AppwriteSdk#299]
### Task Details

- [x] Requests created
- [x] Responses created
- [x] Internal Refit interface created, along with correct order for each endpoint
- [x] Api and interface created - Use Obsolete attribute in interface, and Exclude from code coverage in class
- [x] Tests for all requests and responses
- [x] Double check all requests and responses have full xml docs
- [x] Add inheritdoc to all concrete clients (at the class level)
