### ISSUE TITLE
[Task] Create core for Databases API

### ISSUE THREAD

**Issue by pingu2k4** [PinguApps/AppwriteSdk#388]
### Task Details

- [x] Requests created
- [x] Responses created
- [x] Internal Refit interface created, along with correct order for each endpoint
  - [x] Server
  - [x] Client
- [x] Api and interface created - Use Obsolete attribute in interface, and Exclude from code coverage in class
  - [x] Server
  - [x] Client
- [x] Tests for all requests and responses
- [x] Double check all requests and responses have full xml docs

**Comment by pingu2k4** [comment]
- [ ] Implement Visitor Pattern for Attributes to make it easier to process a list of them.

**Comment by pingu2k4** [comment]
- [ ] Add utils for Permissions, similar to Query and then convert all existing Permissions over
